"""
Local API server for MedLife.

Exposes the database layer (core/database/connection.py) over HTTP so a
frontend can read/write without needing direct DB access.

Run with:
    uvicorn api_server:app --reload --port 8000

Then visit http://localhost:8000/docs for interactive API docs
(generated by FastAPI automatically from the code below).
"""

from contextlib import asynccontextmanager
from datetime import date
from pathlib import Path
from typing import Optional, List, Dict, Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from core.inventory.drug_item import add_drug_item, update_drug_item, delete_drug_item, get_drug_item, list_drug_items

from core.inventory.stock_tracking import update_stock, record_stock_in, record_stock_out, get_stock_history

from core.inventory.reminders import set_reminder, get_upcoming_reminders, auto_generate_expiry_reminders

from core.database.connection import initialize_database, close_database

# --- Startup/shutdown wiring -------------------------------------------------
# FastAPI's lifespan hook replaces manually calling initialize_database()/
# close_database() yourself — it runs once when the server starts and once
# when it shuts down (Ctrl+C).


@asynccontextmanager
async def lifespan(app: FastAPI):
    await initialize_database()
    yield
    await close_database()


app = FastAPI(title="MedLife API", lifespan=lifespan)

# CORS: allows a frontend running on a different port (e.g. a React dev
# server on localhost:3000 or localhost:5173) to call this API. Without
# this, the browser blocks the requests even though the server is running.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten this to your actual frontend's URL once you know it
    allow_methods=["*"],
    allow_headers=["*"],
)


# --- Request/response shapes --------------------------------------------------
# Pydantic models define what JSON shape the frontend sends/receives.
# These mirror DrugItem from models/data_models.py but use FastAPI's
# validation instead of a plain dataclass.

class DrugItemIn(BaseModel):
    id: str
    name: str
    date_of_purchase: date
    date_of_manufacture: date
    expiry_date: date
    batch_number: str
    serial_number: Optional[str] = None
    shelf_location: Optional[str] = None
    company_sourced_from: str = ""
    quantity: int = 0
    price: float = 0.0


class DrugItemUpdate(BaseModel):
    name: Optional[str] = None
    quantity: Optional[int] = None
    price: Optional[float] = None
    shelf_location: Optional[str] = None


# Stock tracking models
class StockRecordIn(BaseModel):
    item_id: str
    quantity_change: int  # Positive for in, negative for out
    timestamp: date
    reason: Optional[str] = None


class StockRecordOut(BaseModel):
    id: str
    item_id: str
    quantity_change: int
    timestamp: date
    reason: Optional[str] = None


# Reminder models
class ReminderIn(BaseModel):
    item_id: str
    reminder_date: date
    type: str  # 'batch', 'expiry', or 'custom'
    message: str


class ReminderOut(BaseModel):
    id: str
    item_id: str
    reminder_date: date
    type: str
    message: str
    is_sent: bool
    sent_at: Optional[date] = None


def _item_to_dict(item) -> dict:
    """Convert a DrugItem dataclass into a plain JSON-serializable dict."""
    return item.__dict__ if item is not None else None


def _stock_record_to_dict(record) -> dict:
    """Convert a StockRecord dataclass into a plain JSON-serializable dict."""
    return record.__dict__ if record is not None else None


def _reminder_to_dict(reminder) -> dict:
    """Convert a Reminder dataclass into a plain JSON-serializable dict."""
    return reminder.__dict__ if reminder is not None else None


# --- Routes --------------------------------------------------------------


# ==================== Drug Item Endpoints ====================


@app.get("/drug-items")
async def list_drug_items(
    expiry_before: Optional[date] = None,
    low_stock_threshold: Optional[int] = None,
    shelf_location: Optional[str] = None,
):
    """List drug items, with optional filters as query params, e.g.
    GET /drug-items?low_stock_threshold=10
    """
    items = await list_drug_items(
        expiry_date_before=expiry_before,
        low_stock_threshold=low_stock_threshold,
        shelf_location=shelf_location,
    )
    return [_item_to_dict(item) for item in items]


@app.get("/drug-items/{item_id}")
async def get_drug_item(item_id: str):
    item = await get_drug_item(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail=f"Drug item '{item_id}' not found")
    return _item_to_dict(item)


@app.post("/drug-items", status_code=201)
async def create_drug_item(item: DrugItemIn):
    # Convert Pydantic model to DrugItem dataclass
    drug_item = DrugItem(
        id=item.id,
        name=item.name,
        date_of_purchase=item.date_of_purchase,
        date_of_manufacture=item.date_of_manufacture,
        expiry_date=item.expiry_date,
        batch_number=item.batch_number,
        serial_number=item.serial_number,
        shelf_location=item.shelf_location,
        company_sourced_from=item.company_sourced_from,
        quantity=item.quantity,
        price=item.price,
    )
    success = await add_drug_item(drug_item)
    if not success:
        raise HTTPException(status_code=500, detail="Failed to create drug item")

    # Fetch the created item to return (including any defaults)
    created_item = await get_drug_item(item.id)
    if created_item is None:
        # This should not happen if the insert succeeded, but handle just in case
        raise HTTPException(status_code=500, detail="Failed to retrieve created drug item")
    return _item_to_dict(created_item)


@app.patch("/drug-items/{item_id}")
async def update_drug_item(item_id: str, updates: DrugItemUpdate):
    # Convert Pydantic model to dict, excluding unset fields
    update_data = updates.model_dump(exclude_unset=True)
    if not update_data:
        raise HTTPException(status_code=400, detail="No fields provided to update")

    success = await update_drug_item(item_id, update_data)
    if not success:
        raise HTTPException(status_code=500, detail="Failed to update drug item")

    # Fetch the updated item to return
    updated_item = await get_drug_item(item_id)
    if updated_item is None:
        # This should not happen if the update succeeded, but handle just in case
        raise HTTPException(status_code=404, detail=f"Drug item '{item_id}' not found after update")
    return _item_to_dict(updated_item)


@app.delete("/drug-items/{item_id}", status_code=204)
async def delete_drug_item(item_id: str):
    success = await delete_drug_item(item_id)
    if not success:
        raise HTTPException(status_code=500, detail="Failed to delete drug item")
    return None


# ==================== Stock Tracking Endpoints ====================


@app.post("/stock-records", status_code=201)
async def create_stock_record(record: StockRecordIn):
    """Record a stock movement (in or out)."""
    # For backward compatibility, we'll use the specific functions based on quantity_change sign
    if record.quantity_change >= 0:
        # Stock in
        success = await record_stock_in(
            item_id=record.item_id,
            quantity=record.quantity_change,
            received_date=record.timestamp
        )
    else:
        # Stock out
        success = await record_stock_out(
            item_id=record.item_id,
            quantity=abs(record.quantity_change),
            used_date=record.timestamp
        )

    if not success:
        raise HTTPException(status_code=500, detail="Failed to record stock movement")

    # Return a confirmation (in a real app, we might fetch the created record)
    return {"status": "Stock movement recorded successfully"}


@app.get("/stock-records/{item_id}", response_model=List[StockRecordOut])
async def get_stock_record_history(
    item_id: str,
    start_date: Optional[date] = None,
    end_date: Optional[date] = None
):
    """Get stock movement history for a specific item."""
    records = await get_stock_history(
        item_id=item_id,
        start_date=start_date,
        end_date=end_date
    )
    return [_stock_record_to_dict(record) for record in records]


# Convenience endpoints for common stock operations
@app.post("/stock/in/{item_id}")
async def stock_in(item_id: str, quantity: int, received_date: date = None):
    """Record stock received for an item."""
    if received_date is None:
        received_date = date.today()

    success = await record_stock_in(
        item_id=item_id,
        quantity=quantity,
        received_date=received_date
    )

    if not success:
        raise HTTPException(status_code=500, detail="Failed to record stock in")

    return {"status": f"Recorded {quantity} units stock in for item {item_id}"}


@app.post("/stock/out/{item_id}")
async def stock_out(item_id: str, quantity: int, used_date: date = None):
    """Record stock used/dispensed for an item."""
    if used_date is None:
        used_date = date.today()

    success = await record_stock_out(
        item_id=item_id,
        quantity=quantity,
        used_date=used_date
    )

    if not success:
        raise HTTPException(status_code=500, detail="Failed to record stock out")

    return {"status": f"Recorded {quantity} units stock out for item {item_id}"}


# ==================== Reminder Endpoints ====================


@app.post("/reminders", status_code=201)
async def create_reminder(reminder: ReminderIn):
    """Create a new reminder for a drug item."""
    success = await set_reminder(
        item_id=reminder.item_id,
        reminder_date=reminder.reminder_date,
        reminder_type=reminder.type
    )

    if not success:
        raise HTTPException(status_code=500, detail="Failed to create reminder")

    # In a full implementation, we would fetch the created reminder to return it
    # For now, we return a success message
    return {"status": "Reminder created successfully"}


@app.get("/reminders", response_model=List[ReminderOut])
async def get_reminders(days_ahead: int = 30):
    """Get upcoming reminders for the next N days."""
    reminders = await get_upcoming_reminders(days_ahead=days_ahead)
    return [_reminder_to_dict(reminder) for reminder in reminders]


@app.post("/reminders/auto-generate")
async def generate_expiry_reminders():
    """Automatically generate expiry reminders for all items expiring soon."""
    count = await auto_generate_expiry_reminders()
    return {"status": f"Generated {count} new expiry reminders"}


# ==================== Health Check Endpoint ====================


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "service": "MedLife API"}


# --- Static Files (Frontend) --------------------------------------------------
# Serve HTML, CSS, and JS from the frontend folder
# This MUST be mounted last, after all API routes, so API routes take precedence
FRONTEND_DIR = Path(__file__).resolve().parent / "frontend"
if FRONTEND_DIR.exists():
    app.mount("/", StaticFiles(directory=str(FRONTEND_DIR), html=True), name="frontend")
else:
    print(f"Warning: frontend directory not found at {FRONTEND_DIR}")